import SwiftUI
import GRDB

struct ProjectAssetsView: View {
    let appDatabase: AppDatabase?
    @Binding var selectedProjectId: UUID?

    @State private var assets: [GeneratedAsset] = []
    @State private var projects: [UUID: String] = [:]
    @State private var isLoading = true
    @State private var selectedAssetId: UUID?
    @State private var filterType: GeneratedAsset.AssetType?
    @State private var searchText = ""
    @State private var isGridMode = true

    private var filteredAssets: [GeneratedAsset] {
        var result = assets
        if let filterType {
            result = result.filter { $0.assetType == filterType }
        }
        if !searchText.isEmpty {
            let query = searchText.lowercased()
            result = result.filter {
                $0.name.lowercased().contains(query)
                || $0.agentType.rawValue.lowercased().contains(query)
                || $0.assetDescription.lowercased().contains(query)
            }
        }
        return result
    }

    private let columns = [GridItem(.adaptive(minimum: 170, maximum: 220), spacing: 12)]

    var body: some View {
        VStack(spacing: 0) {
            ForgeToolbar(title: "Assets") {
                Button {
                    isGridMode.toggle()
                } label: {
                    Image(systemName: isGridMode ? "list.bullet" : "square.grid.2x2")
                }
                .help(isGridMode ? "List View" : "Grid View")
            }
            Divider()

            // Filter bar
            HStack(spacing: 8) {
                // Search
                HStack(spacing: 6) {
                    Image(systemName: "magnifyingglass")
                        .foregroundStyle(.tertiary)
                        .font(.system(size: 12))
                    TextField("Search assets...", text: $searchText)
                        .textFieldStyle(.plain)
                        .font(.system(.subheadline))
                    if !searchText.isEmpty {
                        Button { searchText = "" } label: {
                            Image(systemName: "xmark.circle.fill")
                                .foregroundStyle(.tertiary)
                                .font(.system(size: 12))
                        }
                        .buttonStyle(.plain)
                    }
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 6)
                .background {
                    RoundedRectangle(cornerRadius: 7, style: .continuous)
                        .fill(Color.primary.opacity(0.04))
                        .overlay {
                            RoundedRectangle(cornerRadius: 7, style: .continuous)
                                .strokeBorder(Color.primary.opacity(0.08), lineWidth: 0.5)
                        }
                }

                // Type filters
                filterPill(nil, label: "All")
                filterPill(.document, label: "Docs")
                filterPill(.image, label: "Images")
                filterPill(.video, label: "Videos")
                filterPill(.audio, label: "Audio")
                filterPill(.design, label: "Design")
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 8)

            // Content
            if isLoading && assets.isEmpty {
                ProgressView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else if assets.isEmpty {
                ForgeEmptyState(
                    icon: "photo.on.rectangle.angled",
                    title: "No Assets Yet",
                    subtitle: "Assets generated by creative agents (content, images, videos, designs) will appear here."
                )
            } else if filteredAssets.isEmpty {
                ForgeEmptyState(
                    icon: "magnifyingglass",
                    title: "No Results",
                    subtitle: "No assets match your current filters"
                )
            } else if isGridMode {
                ScrollView {
                    LazyVGrid(columns: columns, spacing: 12) {
                        ForEach(filteredAssets) { asset in
                            AssetCardView(
                                asset: asset,
                                projectName: projects[asset.projectId],
                                isSelected: selectedAssetId == asset.id,
                                onTap: { selectedAssetId = asset.id }
                            )
                        }
                    }
                    .padding(16)
                }
            } else {
                List(filteredAssets, selection: $selectedAssetId) { asset in
                    AssetListRow(asset: asset, projectName: projects[asset.projectId])
                }
                .listStyle(.inset(alternatesRowBackgrounds: true))
            }
        }
        .task {
            await observeAssets()
        }
        .sheet(item: $selectedAssetId) { assetId in
            if let asset = assets.first(where: { $0.id == assetId }) {
                AssetDetailSheet(asset: asset, projectName: projects[asset.projectId], appDatabase: appDatabase)
            }
        }
    }

    // MARK: - Filter Pill

    private func filterPill(_ type: GeneratedAsset.AssetType?, label: String) -> some View {
        let isActive = filterType == type
        return Button {
            filterType = type
        } label: {
            Text(label)
                .font(.system(size: 11, weight: isActive ? .semibold : .medium))
                .foregroundStyle(isActive ? .white : .secondary)
                .padding(.horizontal, 10)
                .padding(.vertical, 4)
                .background {
                    Capsule()
                        .fill(isActive ? Color.accentColor : Color.primary.opacity(0.06))
                }
        }
        .buttonStyle(.plain)
    }

    // MARK: - Observation

    private func observeAssets() async {
        guard let db = appDatabase else { return }
        let observation = ValueObservation.tracking { db in
            let projectFilter = self.selectedProjectId
            var request = GeneratedAsset.order(Column("createdAt").desc)
            if let projectId = projectFilter {
                request = request.filter(Column("projectId") == projectId)
            }
            let assets = try request.fetchAll(db)

            let projectIds = Set(assets.map(\.projectId))
            var names: [UUID: String] = [:]
            for pid in projectIds {
                names[pid] = try Project.fetchOne(db, id: pid)?.name
            }
            return (assets, names)
        }
        do {
            for try await (value, names) in observation.values(in: db.dbQueue) {
                assets = value
                projects = names
                isLoading = false
            }
        } catch {
            isLoading = false
        }
    }
}

// MARK: - UUID Identifiable for sheet

extension UUID: @retroactive Identifiable {
    public var id: UUID { self }
}
